[build]
  command = "pnpm build:all"
  publish = "src/dist"
  functions = "server/dist/netlify-functions"

[dev]
  port = 8888
  functions = "server/dist/netlify-functions"
  framework = "vite"
  command = "pnpm --filter dealvault-pe-frontend dev"
  functionsPort = 9999
  targetPort = 5173

[functions]
  node_bundler = "esbuild"
  
[build.environment]
  NODE_VERSION = "18"
  PNPM_VERSION = "8"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 